Fix Build system for windows native build
Hanjp-IM/libhanjp pull request #16
Opened 2021-08-30 09:38 UTC by thecoder10000

기존에는 linux native에서만 빌드가 가능했지만 windows native에서도 빌드가 가능하게 하기위해 수정함
libhangul이 MinGW에서 사용할 수 있도록 패키징 되어있지 않아서 빌드할 수 있도록 CMake를 다운로드하고 아래의 파일을 수정함

-.gitmodules에 libhangul을 libhanjp의 submodule을 추가함
-CMakeLists.txt에 시스템에서 패키지를 읽던 것에서 서브모듈 소스코드에서 직접 읽도록 바꿈
-hanjpkeyboard.c에 hangul.h를 삭제하고 libhangul을 사용하기위한 선언부를 추가함

2021-08-30 09:45 UTC, JSYoo5B commented
현재 commit 267ee5d47de29fe57201187fda73f4749fd53c59 에서 hangul.h의 코드가 추가되었습니다.

`ucschar` 타입에 대한 정의도 hangul.h에 있기 때문에 수정이 필요할 것 같습니다.

2021-08-30 12:51 UTC, onting commented
네, 제가 @thecoder10000 님께 hangul.h를 인클루드 하는 대신에, 일부 선언을 소스 코드를 직접 옮기라고 알려주었습니다.
왜냐하면 hangul.h를 인클루드 하면 libhanjp 빌드는 되지만 나중에 engine 코드를 작성하기 위해서 hangul.h가 시스템 내부에 설치가 되어야 합니다.
이를 방지하고자 일부 선언을 그냥 소스코드에 박은것인데 @JSYoo5B 님 의견을 고려해보니까, engine은 portable하지 않아도 되기 때문에 페키지 설치하는 것은 큰 문제가 아니고 오히려 선언부를 간단하게 하는 것이 낫다는 생각이 드네요.
@thecoder10000  hangul.h를 인클루드 하는 방식으로 바꾸주실 수 있나요?

2021-08-31 06:47 UTC, onting commented
@thecoder10000 아울러 README도 적절하게 바꿔주세요.

2021-09-01 04:05 UTC, onting commented
README는 submodule를 clone할 때에 같이 다운 받게끔 알려주면 됩니다.

2021-09-01 09:31 UTC, JSYoo5B requested changes

2021-09-01 09:31 UTC, JSYoo5B commented on hanjpkeyboard.c
> +hangul_keyboard_new_from_file(const char* path);
해당 부분은 다시 `hangul.h`를 include 하는 방식으로 변경되었기 때문에, 원본으로 복구하는 것이 좋을 것 같습니다.

2021-09-02 05:14 UTC, onting requested changes
README.md를 살짝 잘못 수정했네요.
제가 말한거는 clone할 때에 그냥 git clone 주소
이런식으로 하면 서브모듈은 다운로드를 받지 않기 때문에 이것도 다운로드 하도록 알려주라는 것이였습니다.
ibus-hanjp의 README도 서브모듈을 다운로드 받기 때문에 거기에서 어떻게 했나 보는게 좋을 것 같네요.

2021-09-02 21:27 UTC, onting approved these changes
잘 된것 같습니다.
수고하셨습니다.

2021-09-02 21:28 UTC, merged