feat[Automata]: Implement to_kana method
Hanjp-IM/libhanjp pull request #18
Opened 2021-09-02 15:22 UTC by catensia

- Implement to_kana method based on cpp code
- Added necessary parts of hangul unicode, HANJP_CHOSEONG_FILLER and HANJP_JUNSEONG_FILLER

2021-09-02 15:39 UTC, JSYoo5B requested changes

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> -} JungBox;
이 부분은 기존 267ee5d47de29fe57201187fda73f4749fd53c59 에서 refactoring 하면서 변경된 부분입니다.
현재 commit에서 직접 수정하는 것 보다, rebase하는 것을 추천드립니다.

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> +
이 부분은 기존 267ee5d 에서 refactoring 하면서 변경된 부분입니다.
현재 commit에서 직접 수정하는 것 보다, rebase하는 것을 추천드립니다.

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> -
이 부분은 기존 267ee5d 에서 refactoring 하면서 변경된 부분입니다.
현재 commit에서 직접 수정하는 것 보다, rebase하는 것을 추천드립니다.

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> +
이 부분은 기존 267ee5d 에서 refactoring 하면서 변경된 부분입니다.
현재 commit에서 직접 수정하는 것 보다, rebase하는 것을 추천드립니다.

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> +                jong = hangul_choseong_to_jonseong(cho);
함수 이름에 오타가 있습니다.

`hangul_choseong_to_jongseong` 입니다.

2021-09-02 15:39 UTC, JSYoo5B commented on hanjpautomata.c
> +                cho = hangul_jongseong_to_choseong(jong);
현재 여기서 호출된 `hangul_jongseong_to_choseong`과 `hangul_choseong_to_jongseong` 함수는 libhangul에 정의된 함수입니다.

하지만 이 두 함수는 libhangul이 제공하는 헤더인 hangul.h에서 위 두 함수의 원형에 대한 선언이 없어, 컴파일 과정에서 문제가 생길 수도 있습니다.

이전 267ee5d47de29fe57201187fda73f4749fd53c59 commit에서 해당 함수 사용을 위해 원형을 다시 선언했으니, 해당 부분을 확인 바랍니다.

[코드](https://github.com/Hanjp-IM/libhanjp/blob/1534c8de16/hanjpautomata.c#L6-L8)

2021-09-02 15:42 UTC, JSYoo5B commented
PR 작성하느라 고생하셨습니다.

조금 더 좋은 PR 과 commit 기록을 남기기 위해 리뷰를 했으니, 확인해보시고 모르는 부분 있다면 질문해주시기 바랍니다.

2021-09-02 15:44 UTC, catensia commented
모자란 PR 리뷰 감사합니다.

말씀해주신 지적들 반영해보도록 하겠습니다.

2021-09-04 03:48 UTC, JSYoo5B requested changes

2021-09-04 03:48 UTC, JSYoo5B commented on hanjpautomata.c
> +                g_array_append_val(dest, kana_table[HANJP_CONSONANT_T][HANJP_VOWEL_U]-1); break;
현재 이 부분에서 컴파일 오류가 발생하고 있습니다.

https://github.com/Hanjp-IM/libhanjp/pull/18/checks?check_run_id=3511675779

2021-09-04 03:49 UTC, JSYoo5B commented
다른 코드 수정사항은 모두 괜찮은 것 같습니다.

현재 빌드 오류가 발생하는 부분을 설명해놨으니, 이 부분 확인해보셔야 할 것 같습니다.

2021-09-04 04:07 UTC, catensia commented on hanjpautomata.c
> +                g_array_append_val(dest, kana_table[HANJP_CONSONANT_T][HANJP_VOWEL_U]-1); break;
확인 감사합니다. 
반영했습니다.

2021-09-04 05:07 UTC, JSYoo5B approved these changes

2021-09-04 10:57 UTC, JSYoo5B commented
@onting PR 확인하시고 merge 해주세요!

2021-09-04 11:14 UTC, onting commented
destlen, c는 불필요합니다.
tempkey의 선언을 처음에 해주세요.
왜냐하면 과도한 변수 남용을 막기 위해서 선언을 맨 처음에 하는 것을 선호하고 있습니다.

2021-09-05 04:45 UTC, onting commented
아마 코멘트 달아 놓은 부분만 고치면 맞게 작성된것 같습니다

2021-09-06 02:57 UTC, catensia commented
코멘트 달아주신 부분 수정하였습니다.

2021-09-06 03:08 UTC, onting approved these changes
수고하셨습니다.
제가 까탈스럽게 요청을 많이 했는데 잘 해주셨습니다.

2021-09-06 03:08 UTC, merged