feat[Automata] Impl. flush()
Hanjp-IM/libhanjp pull request #21
Opened 2021-09-08 10:02 UTC by catensia

- Implement ambase flush() method
- Based on cpp reference code

2021-09-08 10:15 UTC, JSYoo5B requested changes

2021-09-08 10:15 UTC, JSYoo5B commented on hanjpautomata.c
> +    return signal;
이 부분은 아직 수정하지 않고 원본으로 두는게 나을 것 같습니다

2021-09-08 10:35 UTC, catensia commented on hanjpautomata.c
> +    return signal;
확인 감사합니다.
반영하였습니다.

2021-09-08 10:39 UTC, JSYoo5B approved these changes
LGTM

2021-09-09 07:24 UTC, onting approved these changes
LGTM

2021-09-09 07:24 UTC, merged